.\"	$Id$
.\"
.\" Copyright (c) 2013 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt SBLG 1
.Os
.Sh NAME
.Nm sblg
.Nd simple off-line blog utility
.Sh SYNOPSIS
.Nm sblg
.Op Fl C Ar file
.Op Fl o Ar file
.Op Fl t Ar template
.Op Fl ac
.Ar
.Sh DESCRIPTION
The
.Nm
utility knits together XML articles and templates in four ways.
.Bl -bullet
.It
Standalone mode
.Pq Fl c
links single articles with a template with an article stub, which is
filled in with the article.
For example,
.Qq sblg -c foo.xml bar.xml
creates
.Pa foo.html
and
.Pa bar.html
from a template populated by the
.Pa foo.xml
and
.Pa bar.xml
article contents, respectively.
.It
Blog amalgamation mode links multiple articles with a template
consisting of articles and navigation stubs.
For example,
.Qq sblg -o foo.html bar.html baz.html
links
.Pa bar.html
and
.Pa baz.html
into
.Pa foo.html
from a template.
.It
Atom amalgamation mode
.Pq Fl a
link multiple articles with an Atom feed template.
.It
Standalone amalgamation mode
.Pq Fl C
links multiple articles in standalone style, i.e., multiple navigation
stubs, a single article stub.
For example,
.Qq sblg -o foo.html -C bar.html baz.html bar.html
will show only
.Pa bar.html
in the article list of
.Pa foo.html ,
but both
.Pa bar.html
and
.Pa baz.html
in its navigation.
.El
.Pp
By default,
.Nm
operates as blog amalgamation mode, specifically as if
.Qq sblg -o blog.html -t blog-template.xml ...
were specified.
Its arguments are as follows:
.Bl -tag -width Ds
.It Fl C Ar file
Like
.Fl c ,
but creating a blog amalgamation.
In effect, an amalgamation with a single
.Aq article data-sblg-article="1" .
Ignored when used with
.Fl a
or
.Fl c .
.It Fl o Ar file
Output file.
If unspecified, standalone articles have
.Li .html
appended to the input file name, unless the input file extension is
.Li .xml ,
in which case the
.Li .xml
is replaced by
.Li .html .
If multiple input files are specified,
.Fl o
is ignored.
If unspecified for the blog amalgamation,
.Ar blog.html
is used by default.
If unspecified for the Atom feed amalgamation,
.Ar atom.xml
is used by default.
Use
.Fl o Ar \-
for standard output.
.It Fl t Ar template
Template for standalone or amalgamation files.
If unspecified, defaults to
.Ar article-template.xml
for
.Fl c ,
.Ar atom-template.xml
for
.Fl a ,
and
.Ar blog-template.xml
otherwise.
.It Fl a
Creates an Atom feed amalgamation from its input files.
.It Fl c
Create standalone articles instead of merging together articles into an
amalgamation.
.It Ar
Input files.
In standalone mode with
.Fl c ,
input XML files are merged with a template into an output file.
Otherwise, multiple input files are merged into a single amalgamation.
.El
.Pp
All input and output must be well-formed XML.
HTML is assumed only with the default suffix re-write rule for
.Fl c
without
.Fl o .
Input articles may be XML fragments or full documents: only the
.Aq article data-sblg-article="1"
tree within the article is considered.
.Ss Article Input
Article input files consist of XML fragments or whole documents.
They must at least consist of the following within the document:
.Bd -literal
<article data-sblg-article="1">
  <header>
    <h1>Article Name</h1>
    <address>Author Name</address>
    <time datetime="2013-06-29">29 June, 2013</time>
  </header>
  <aside>
    This is used as the feed <b>content</b>.
  </aside>
  <p>Some text.</p>
</article>
.Ed
.Pp
When processed with
.Nm ,
all data outside of the
.Aq article data-sblg-article="1"
element is discarded.
Then the article title (both as text data only and inclusive of markup)
is extracted from the first
.Aq hn
.Pq header 1\(en4 ,
article publication date is extracted from the first
.Aq time ,
and author (both as text data only and inclusive of markup) from the
first
.Aq address .
At any point, if a tag has an
.Li data-sblg-tags
attribute consisting of space-separated tag names, these tags are
extracted for tag operation.
.Pp
If unspecified, the default article title text (and mark-up) is
.Qq Untitled article ,
the default author text (and mark-up) is the
.Qq Unknown author ,
the publication time is set to the document's file-system creation time,
and no tags.
.Pp
The first
.Aq aside ,
if provided, is used for the feed content.
All content is recorded in case the
.Li data-sblg-content
Boolean value is used in an Atom feed.
.Ss Standalone Template
The standalone template file must be a well-formed XML file where the
first
.Aq article data-sblg-article="1"
element is replaced by the article text.
All of this element's children are removed.
.Bd -literal
<body>
  <header>This consists of a single blog entry.</header>
  <article>This is kept.</article>
  <article data-sblg-article="1">This is removed.</article>
  <footer>Something.</footer>
</body>
.Ed
.Pp
See
.Sx Tag Symbols
for a list of symbols that will be replaced if found in attribute value
or textual contexts.
.Ss Blog Amalgamation Template
The amalgamation template file must also be a well-formed XML file where
each
.Aq article data-sblg-article="1"
element is replaced by ordered (newest to oldest) article text.
If there aren't enough articles, the element is removed.
Furthermore, any
.Aq nav data-sblg-nav="1"
elements are replaced by a list of all available articles in an
unordered list consisting of article dates followed by the title text,
linked to the page itself.
.Po
.Em Note :
if you're running
.Fl o
with XML files, the linked file will consist of an XML target, not
an HTML target.
.Pc
.Pp
The Boolean
.Li data-sbgl-navcontent
attribute makes the content of the
.Aq nav
be replaced as specified in
.Sx Tag Symbols .
.Pp
If the
.Aq nav
element contains a positive integer
.Li data-sblg-navsz
attribute, this is used to limit the number of navigation entries.
Finally, if the
.Li data-sblg-navtag
is specified, only articles with matching tags are shown.
You can specify multiple space-separated tags, for instance,
.Li data-sblg-navtag="foo bar"
will search for foo or bar.
Tags to be matched against are extracted from the space-separated
.Li data-sblg-tags
element of each article's topmost
.Aq article
element.
.Bd -literal
<body>
  <header>This consists of two blog entries.</header>
  <nav data-sblg-nav="1" />
  <article data-sblg-article="1" />
  <article data-sblg-article="1" />
  <footer>Something.</footer>
</body>
.Ed
.Pp
Each
.Aq article
will be followed by a
.Pq permanent link
anchor within a
.Aq div
with the custom class
.Qq data-sblg-permlink
unless a Boolean
.Qq data-sblg-permlink
attribute is set to false.
.Em Note :
the permanent link is set to the article name, so if you specify an XML
file, it will be to an XML file!
.Ss Standalone Amalgamation Template
This is identical to the
.Sx Blog Amalgamation Template
except that a single article is noted with
.Fl C ,
and this is the only article displayed in the article stub.
In the given example,
.Bd -literal
<body>
  <header>This consists of two blog entries.</header>
  <nav data-sblg-nav="1" />
  <article data-sblg-article="1" />
  <article data-sblg-article="1" />
  <footer>Something.</footer>
</body>
.Ed
.Pp
the navigation would be populated by all articles, but only the first
article stub would be filled in with the specified article.
The second would be removed.
.Ss Atom Amalgamation Template
The Atom template file must be a well-formed XML file where each
.Aq entry
element with a Boolean
.Li data-sblg-entry
attribute is replaced by ordered (newest to oldest) article information.
If there aren't enough articles, the element is removed.
.Bd -literal
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>Example Feed</title>
  <link href="http://example.org/feed/" rel="self" />
  <link href="http://example.org/" />
  <updated data-sblg-updated="1" />
  <id data-sblg-id="1" />
  <entry data-sblg-entry="1" />
  <entry data-sblg-entry="1" />
  <entry data-sblg-entry="1" />
</feed>
.Ed
.Pp
The
.Aq updated
element with a Boolean
.Li data-sblg-updated
attribute is replaced with the newest article date (or the current date,
if no articles are listed).
The
.Aq id
element with a Boolean
.Li data-sblg-id
attributed is replaced with an identifier in the form of
.Li tag:domain,2013:path ,
where the domain is initialised to the current domain or extracted from
the
.Aq link
to the self.
The path is also extracted from the self
.Aq link ,
initialised to the root path
.Sq \&/ .
.Pp
Each
.Aq entry
element with a Boolean
.Li data-sblg-entry
attribute is filled in with a
.Aq title ,
.Aq id
.Pq in tag format ,
.Aq author ,
HTML
.Aq content
.Pq specified in the article as an Ao aside Ac ,
and alternate
.Aq link .
If the
.Ar entry
element contains a false
.Li data-sblg-altlink
Boolean attribute, the alternate
.Aq link
is not printed.
Furthermore, if a true
.Li data-sblg-content
Boolean attribute exists, the article's contents (everything within the
.Aq article data-sblg-article="1" )
are inlined within the
.Aq content
element with type
.Li html .
.Pp
No
.Sx Tag Symbols
are processed.
.Ss Tag Symbols
Within the template for
.Fl c
or
.Fl C ,
or in any article contents written (either into an article or navigation
entry), the following special strings are replaced.
These symbols concern the current article being processed: in a
navigation entry, or as article contents.
In the event of the positional
.Dq next
and
.Dq prev
symbols, these refer to the article's position within the input
articles.
Obviously,
.Fl c
has only a single article.
.Bl -tag -width -Ds
.It Li ${sblg-aside}
The article's first aside with markup.
.It Li ${sblg-asidetext}
The article's first aside, textual parts only.
.It Li ${sblg-author}
The article's author with markup.
.It Li ${sblg-authortext}
The article's author, textual parts only
.It Li ${sblg-base}, Li ${sblg-stripbase}
The full filename (including directory) with the last suffix part
chopped off.
For example,
.Pa foo/bar.xml
becomes
.Pa foo/bar .
The stripped version will strip off the directory part.
For example,
.Pa foo/bar.xml
becomes
.Pa bar .
.It Li ${sblg-date}
The publication date.
.It Li ${sblg-first-base}, Li ${sblg-first-stripbase}
The first (newest) base name in the list of articles.
.Pq See Li ${sblg-base} .
.It Li ${sblg-last-base}, Li ${sblg-last-stripbase}
The last (oldest) base name in the list of articles.
.Pq See Li ${sblg-base} .
.It Li ${sblg-next-base}, Li ${sblg-next-stripbase}
The next base name when chronologically ordered from newest to oldest,
wrapping back to the beginning for the last.
.Pq See Li ${sblg-base} .
.It Li ${sblg-prev-base}, Li ${sblg-prev-stripbase}
The previous base name when chronologically ordered from newest to
oldest, wrapping back to the beginning for the last.
.Pq See Li ${sblg-base} .
.It Li ${sblg-source}
The source file when passed for parsing.
.It Li ${sblg-title}
The article title with markup.
.It Li ${sblg-titletext}
The article title, textual parts only.
.It Li ${sblg-url}
The output filename, which is empty for standard output.
.El
.Pp
Be careful in using these: the contents are copied directly, so if
specifying a value within an HTML attribute that has a double-quote, the
attribute will be prematurely closed.
.Sh FILES
.Bl -tag -width Ds
.It Pa article-template.xml
Default template for creating articles with
.Fl c .
.It Pa atom-template.xml
Default template for creating atom feeds with
.Fl a .
.It Pa blog-template.xml
Default template for creating a front page.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
First, create standalone HTML5 files from article fragments.
An
.Pa article-template.xml
file is assumed to exist.
.Pp
.Dl % sblg -c article1.xml article2.xml
.Pp
Next, merge formatted files into a front page.
A
.Pa blog-template.xml
file is assumed to exist.
.Pp
.Dl % sblg -o index.html article1.html article2.html
.Sh STANDARDS
Input files and templates must be properly-formed XML files.
Output files are guranteed to be XML as well.
The Atom file template must be well-formed; output is guaranteed to
satisfy the Atom 1.0 and Tag ID standards.
.Sh AUTHORS
The
.Nm
utility was written by
.An Kristaps Dzonsons ,
.Mt kristaps@bsd.lv .
.Sh CAVEATS
Boolean XML values must have an attribute specified.
In other words,
.Aq foo bar="1"
is valid, while
.Aq foo bar
is not.
